### ISSUE TITLE
Default style of canvas element

### ISSUE THREAD

**Issue by skybber** [cds-astro/aladin-lite#213]
Aladin modifies default style of all canvases on the page:

```css
canvas {
    image-rendering: optimizeSpeed;
    image-rendering: -moz-crisp-edges;
    image-rendering: -webkit-optimize-contrast;
    image-rendering: -o-crisp-edges;
    image-rendering: pixelated;
    -ms-interpolation-mode: nearest-neighbor;
}
```

It would be better to have a selector for the Aladin canvas otherwise it worsens the rendering quality (at least in FF/windows11) in non Aladin canvases.
